name: Format

on:
  push:
    branches:
      - main

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swift_format:
    name: swift-format
    runs-on: macos-13
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Xcode Select
        run: sudo xcode-select -s /Applications/Xcode_14.3.1.app
      - name: Install
        run: brew install swift-format
      - name: Format
        run: make format
      - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9  # v7.1.0
        with:
          commit_message: Run swift-format
          branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
